include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

aws {
  region = us-east-1
  accountId = 000000000000
}

messages-storage {
  enabled = true
}

queues {
  "video-processing" {
    defaultVisibilityTimeout = 900 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "video-processing-dlq"
      maxReceiveCount = 3
    }
  }
  "video-processing-dlq" { }
}
